// Question catalogue for the event wizard, keyed by GAME language (not the UI
// locale) — a German game can be built from an English interface and vice versa.
export const QUESTION_CATALOG: Record<string, string[]> = {
  de: [
    'Wer ist morgens schlechter gelaunt?',
    'Wer räumt öfter die Spülmaschine aus?',
    'Wer kann besser kochen?',
    'Wer weint zuerst beim Ja-Wort?',
    'Wer gibt im Streit zuerst nach?',
    'Wer verbringt länger im Bad?',
    'Wer vergisst eher den Hochzeitstag?',
    'Wer ist das größere Kind?',
    'Wer trifft die besseren Entscheidungen?',
    'Wer ist der bessere Autofahrer?',
    'Wer gibt mehr Geld aus?',
    'Wer schnarcht lauter?',
    'Wer ist romantischer?',
    'Wer hat die verrückteren Ideen?',
    'Wer räumt nie auf?',
    'Wer ist eifersüchtiger?',
    'Wer sagt öfter «Ich liebe dich»?',
    'Wer schläft abends zuerst ein?',
    'Wer checkt öfter das Handy?',
    'Wer ist der größere Morgenmuffel?',
    'Wer kann besser mit Geld umgehen?',
    'Wer telefoniert länger mit der Familie?',
    'Wer ist öfter zu spät?',
    'Wer hat mehr Schuhe?',
    'Wer singt lauter unter der Dusche?',
    'Wer bestellt im Restaurant das Bessere?',
    'Wer ist der bessere Tänzer?',
    'Wer packt den Koffer schneller?',
    'Wer wird schneller wütend?',
    'Wer entschuldigt sich zuerst?',
    'Wer ist der größere Feinschmecker?',
    'Wer verschläft öfter den Wecker?',
    'Wer plant den nächsten Urlaub?',
    'Wer ist ordentlicher?',
    'Wer lacht über die eigenen Witze?',
    'Wer kann besser flirten?',
    'Wer isst den letzten Bissen vom Teller des anderen?',
    'Wer gibt beim Serienabend die Fernbedienung nicht her?',
    'Wer ist abenteuerlustiger?',
    'Wer kann besser Geheimnisse für sich behalten?',
    'Wer trinkt mehr Kaffee?',
    'Wer ist die größere Leseratte?',
    'Wer verliert öfter die Schlüssel?',
    'Wer gewinnt beim Brettspiel?',
    'Wer ist spontaner?',
    'Wer kann besser einparken?',
    'Wer redet mehr im Schlaf?',
    'Wer ist der bessere Gastgeber?',
    'Wer gibt bei Diskussionen nie klein bei?',
    'Wer würde eher eine Reality-Show gewinnen?',
  ],
  en: [
    "Who's grumpier in the morning?",
    'Who empties the dishwasher more often?',
    "Who's the better cook?",
    "Who cries first at the 'I do'?",
    'Who gives in first in an argument?',
    'Who spends longer in the bathroom?',
    "Who's more likely to forget the anniversary?",
    "Who's the bigger kid?",
    'Who makes the better decisions?',
    "Who's the better driver?",
    'Who spends more money?',
    'Who snores louder?',
    "Who's more romantic?",
    'Who has the crazier ideas?',
    'Who never tidies up?',
    "Who's more jealous?",
    "Who says 'I love you' more often?",
    'Who falls asleep first at night?',
    'Who checks their phone more often?',
    "Who's the bigger morning grump?",
    "Who's better with money?",
    'Who talks on the phone with family longer?',
    "Who's late more often?",
    'Who owns more shoes?',
    'Who sings louder in the shower?',
    'Who orders better at a restaurant?',
    "Who's the better dancer?",
    'Who packs a suitcase faster?',
    'Who gets angry more quickly?',
    'Who apologises first?',
    "Who's the bigger foodie?",
    'Who oversleeps more often?',
    'Who plans the next holiday?',
    "Who's tidier?",
    'Who laughs at their own jokes?',
    "Who's the better flirt?",
    "Who eats the last bite off the other's plate?",
    "Who won't hand over the remote on TV night?",
    "Who's more adventurous?",
    "Who's better at keeping secrets?",
    'Who drinks more coffee?',
    "Who's the bigger bookworm?",
    'Who loses their keys more often?',
    'Who wins at board games?',
    "Who's more spontaneous?",
    "Who's better at parking?",
    'Who talks more in their sleep?',
    "Who's the better host?",
    'Who never backs down in a debate?',
    "Who's more likely to win a reality show?",
  ],
}

export function getCatalog(language: string): string[] {
  return QUESTION_CATALOG[language] ?? QUESTION_CATALOG.de
}
