// Question catalogue for the event wizard, keyed by GAME language (not the UI
// locale) — a German game can be built from an English interface and vice versa.
export const QUESTION_CATALOG: Record<string, string[]> = {
  de: [
    'Wer braucht länger im Bad?',
    'Wer würde eher den Hochzeitstag vergessen?',
    'Wer neigt dazu, bei einem Streit eher nachzugeben?',
    'Wer würde sich eher beim Hochzeitstanz vertanzen?',
    'Wer würde eher morgens den Wecker fünfmal snoozen?',
    'Wer würde eher über den eigenen Witz lachen?',
    'Wer ist der größere Morgenmuffel?',
    'Wer würde eher ein Geheimnis nicht geheim halten können?',
    'Wer würde eher den Abwasch «vergessen»?',
    'Wer ist der größere Sturkopf?',
    'Wer würde eher vergessen, wo er/sie den Schlüssel hingelegt hat?',
    'Wer würde eher die Wäsche tagelang im Trockner liegen lassen?',
    'Wer schreibt die süßeren Nachrichten?',
    'Wer würde eher aus Versehen etwas Buntes in die Weißwäsche werfen?',
    'Wer würde eher aus dem Nichts anfangen zu singen?',
    'Wer ist der/die größere Chaot:in?',
    'Wer ist der größere Tollpatsch?',
    'Wer würde eher zu spät kommen?',
    'Wer ist ordentlicher?',
    'Wer ist romantischer?',
    'Wer würde eher wegen einer Kleinigkeit diskutieren?',
    'Wer würde eher «Ist schon gut» sagen und es doch nicht meinen?',
    'Wer würde sich eher verlaufen?',
    'Wer würde eher stolpern, ohne dass etwas im Weg liegt?',
    'Wer hat den schlechteren Musikgeschmack?',
    'Wer war heute nervöser vor dem Ja-Wort?',
    'Wer ist der/die bessere Autofahrer:in?',
    'Wer würde eher das Essen anbrennen lassen?',
    'Wer verbringt mehr Zeit am Handy?',
    'Wer würde eher etwas kaufen, das man nie benutzt?',
    'Wer würde eher beim Wandern zuerst schlappmachen?',
    'Wer würde eher bei einem Spiel schummeln?',
    'Wer wäre bei einer Wette der/die schlechtere Verlierer:in?',
    'Wer würde eher einen Geburtstag vergessen?',
    'Wer klaut nachts die Bettdecke?',
    'Wer würde eher im Kino einschlafen?',
    'Wer weint eher bei einem Film?',
    'Wer bleibt in stressigen Situationen ruhiger?',
    'Wer bringt den anderen öfter zum Lachen?',
    'Wer hat mehr für die Hochzeit organisiert?',
    'Wer hat bei der Verlobung mehr geweint?',
    'Wer würde eher die Rede vergessen?',
    'Wer würde eher unter der Dusche singen?',
    'Wer jammert mehr bei einer Erkältung?',
    'Wer würde eher eine ganze Serie an einem Tag durchschauen?',
    'Wer flutet eher das Handy des anderen mit Reels?',
    'Wer würde eher «aus Versehen» unter der Bettdecke pupsen?',
    'Wer würde eher sagen, dass er/sie die Hosen anhat?',
    'Wer würde eher als Letztes die Party verlassen?',
    'Wer würde eher über die Socken auf dem Boden steigen, statt sie aufzuheben?',
  ],
  en: [
    "Who's grumpier in the morning?",
    'Who empties the dishwasher more often?',
    "Who's the better cook?",
    "Who cries first at the 'I do'?",
    'Who gives in first in an argument?',
    'Who spends longer in the bathroom?',
    "Who's more likely to forget the anniversary?",
    "Who's the bigger kid?",
    'Who makes the better decisions?',
    "Who's the better driver?",
    'Who spends more money?',
    'Who snores louder?',
    "Who's more romantic?",
    'Who has the crazier ideas?',
    'Who never tidies up?',
    "Who's more jealous?",
    "Who says 'I love you' more often?",
    'Who falls asleep first at night?',
    'Who checks their phone more often?',
    "Who's the bigger morning grump?",
    "Who's better with money?",
    'Who talks on the phone with family longer?',
    "Who's late more often?",
    'Who owns more shoes?',
    'Who sings louder in the shower?',
    'Who orders better at a restaurant?',
    "Who's the better dancer?",
    'Who packs a suitcase faster?',
    'Who gets angry more quickly?',
    'Who apologises first?',
    "Who's the bigger foodie?",
    'Who oversleeps more often?',
    'Who plans the next holiday?',
    "Who's tidier?",
    'Who laughs at their own jokes?',
    "Who's the better flirt?",
    "Who eats the last bite off the other's plate?",
    "Who won't hand over the remote on TV night?",
    "Who's more adventurous?",
    "Who's better at keeping secrets?",
    'Who drinks more coffee?',
    "Who's the bigger bookworm?",
    'Who loses their keys more often?',
    'Who wins at board games?',
    "Who's more spontaneous?",
    "Who's better at parking?",
    'Who talks more in their sleep?',
    "Who's the better host?",
    'Who never backs down in a debate?',
    "Who's more likely to win a reality show?",
  ],
}

export function getCatalog(language: string): string[] {
  return QUESTION_CATALOG[language] ?? QUESTION_CATALOG.de
}
